### ISSUE TITLE
Remove mapping types

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-cli#47]
As part of v2.0 release, `mapping types` are getting removed from OpenSearch engine. Below are the changes in the opensearch-engine.
- Removal of type from rest end-points
- Removal of include_type_name parameter from API requests.

As part of this issue, please verify if type removal change on OpenSearch engine impacts this repository. If yes, then please remove the type references/usage from this repository

Top level changes are captured in gist below: 
https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

For more detailed changes, please check meta issue below:
Related: [OpenSearch-engine meta issue](https://github.com/opensearch-project/opensearch/issues/1940)

**Comment by VijayanB** [comment]
CLI doesn't use any rest endpoint which uses mapping type/include_type_name.

**Comment by dreamer-89** [comment]
@VijayanB : Did you get a chance to go through all the changes captured in gist ? There are some changes in rest client, internal server classes which are used abundantly in other plugin repos. 
https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

**Comment by VijayanB** [comment]
> @VijayanB : Did you get a chance to go through all the changes captured in gist ? There are some changes in rest client, internal server classes which are used abundantly in other plugin repos. https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

CLI accepts mapping as dynamic value from the user input. I added an integration test against OpenSearch 2.0. It didn't fail as expected.
