### ISSUE TITLE
Release OpenSearch CLI 1.2.0

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-cli#58]
Release binary for MacOS/Windows/Linux x64/arm64

**Comment by VachaShah** [comment]
The release process is currently in progress. See https://github.com/opensearch-project/opensearch-build/issues/4185

**Comment by VachaShah** [comment]
Version 1.2.0 is released https://github.com/opensearch-project/opensearch-cli/releases/tag/v1.2.0
