### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-cli#70]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by wbeckler** [comment]
It looks like codeowners needs updating. The repo permissions match https://github.com/opensearch-project/opensearch-cli/blob/main/MAINTAINERS.md

**Comment by wbeckler** [comment]
@VachaShah would you be willing to take this on? Step 1: get yourself added as a maintainer in Maintainers.md. Step 2: request an admin to add you to the repo maintainers. Step 3: fix codeowners.

**Comment by VachaShah** [comment]
> @VachaShah would you be willing to take this on? Step 1: get yourself added as a maintainer in Maintainers.md. Step 2: request an admin to add you to the repo maintainers. Step 3: fix codeowners.

@wbeckler Sure!

**Comment by dblock** [comment]
Permissions verified.

<img width="859" alt="Screenshot 2023-05-10 at 5 48 00 PM" src="https://github.com/opensearch-project/opensearch-cli/assets/542335/0fbcffe9-e705-4955-9b40-af24b6724dd1">

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-cli/pull/83.
