### ISSUE TITLE
[BUG] CLI cannot create/send multipart POST REST request (from file)

### ISSUE THREAD

**Issue by jnschbrt** [opensearch-project/opensearch-cli#76]
**What is the bug?**
My goal is to use opensearch-cli to import the `/_dashboards/api/saved_objects/_import` REST API 
However, the API expects the POST request with content-type: multipart/form-data

See: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/core/server/saved_objects/routes/import.ts

The Opensearch CLI only offers the possibility to specify a file with the --data flag. Native CURL commands offer the possibility to specify the file via --data-binary flag. 

The CURL POST command generated by the Opensearch CLI cannot automatically set the multipart boundary, so the post command fails as follows:

I use the authenticated curl post command here as follows:
#### Without providing headers

`opensearch-cli curl post --profile local  --path "/_dashboards/api/saved_objects/_import" --data @export.ndjson`
Error:
```
{
  "error": "Unsupported Media Type",
  "message": "Unsupported Media Type",
  "statusCode": 415
}
```

#### Providing multipart-form-data header
`opensearch-cli curl post --profile local --path "/_dashboards/api/saved_objects/_import" -H "content-type:multipart/form-data;"  --data @export.ndjson`
Error:
```
{
  "error": "Bad Request",
  "message": "Invalid content-type header: multipart missing boundary",
  "statusCode": 400
}
```
#### Providing multipart-form-data header and any random boundary
`opensearch-cli curl post --profile local --path "/_dashboards/api/saved_objects/_import" -H "content-type:multipart/form-data; boundary:something;"  --data @export.ndjson`
Error:
```
{
  "error": "Bad Request",
  "message": "Invalid content-type header: multipart missing boundary",
  "statusCode": 400
}
```

**How can one reproduce the bug?**
1. Export any saved objects via Opensearch Web UI
2. Try to import these using the cli curl commands above

**What is your host/environment?**
 - OS: ubuntu
 - Version 20.04.5 LTS
 - Opensearch-cli version 1.1.0 linux/amd64
 - OpenSearch version 2.3.0

**Comment by wbeckler** [comment]
This looks worth fixing. Feel free to submit a PR.

**Comment by wbeckler** [comment]
@VachaShah would you be willing to do a release?

**Comment by VachaShah** [comment]
We have a release planned for today for 1.2.0.

**Comment by VachaShah** [comment]
We have the release process in progress but figuring out some issues along the way. Build release issue: https://github.com/opensearch-project/opensearch-build/issues/4185

**Comment by VachaShah** [comment]
Version 1.2.0 is released: https://github.com/opensearch-project/opensearch-cli/releases/tag/v1.2.0
