### ISSUE TITLE
[BUG] Failing test case due to incorrect error text

### ISSUE THREAD

**Issue by zethuman** [opensearch-project/opensearch-cli#78]
**What is the bug?**
Test case failing cause new error text added, but expected result not updated in tests #66 

**How can one reproduce the bug?**
1. Run tests locally or go to actions of project

**What is the expected behavior?**
Successfully passed tests

**What is your host/environment?**
 - OS: [macos]
 - Version [13.3.1 (22E261)]
 - OpenSearch version[latest]

**Comment by VachaShah** [comment]
Hi @zethuman, #66 was fixed via PR #97. Does that resolve your issue?

**Comment by zethuman** [comment]
Basically, yes it does. Actually, does this repository accept pull requests or is it just the maintainer who fixes the bugs himself?

**Comment by VachaShah** [comment]
Thank you @zethuman for the confirmation. We surely accept all pull requests!

**Comment by VachaShah** [comment]
Fixed in PR #84
