### ISSUE TITLE
[FEATURE] Update codecov action

### ISSUE THREAD

**Issue by zethuman** [opensearch-project/opensearch-cli#82]
**Is your feature request related to a problem?**
_We are having [problems](https://github.com/opensearch-project/opensearch-cli/actions/runs/4929546746/jobs/8809312932) with codecov in our current CI/CD project. This is a known issue in the tools repository and it is recommended to update to the new version._

**What solution would you like?**
Update codecov to latest version

**Do you have any additional context?**
I would be happy to take on the choice of the optimal version for current project

**Comment by VachaShah** [comment]
Done via #84
