### ISSUE TITLE
[BUG] cannot create/send multipart POST REST request (from file)

### ISSUE THREAD

**Issue by ghost** [opensearch-project/opensearch-cli#93]
**What is the bug?**
A clear and concise description of the bug.

**How can one reproduce the bug?**
3. Enter following curl command '...'

**What is the expected behavior?**

**What is your host/environment?**
 - OS: [e.g. ubuntu]
 - Version [e.g. 20.10]
 - Plugin version [e.g. 1.1.0]
 - OpenSearch version[e.g. 1.0.0]
 
**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)

**Comment by dblock** [comment]
Closing, not enough detail of what's happening here.
